# Generated by Django 5.1.7 on 2025-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
