# Generated by Django 5.1.7 on 2025-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='url',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credentials',
            name='enable',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
