# Generated by Django 5.1.7 on 2025-03-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_credentials_url_alter_credentials_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='enable',
        ),
        migrations.AddField(
            model_name='credentials',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
