# Generated by Django 5.1.7 on 2025-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_credentials_enable_credentials_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
